### ISSUE TITLE
Consider agent association

### ISSUE THREAD

**Issue by garemoko** [kirstykitto/CLRecipe#10]
It makes sense for this recipe to use the learner's account on each social media platform to send statements about that platform. This presents a problem though: how do we know that Aneesha on Twitter is the same as Aneesha on Facebook?

The solution that's been suggested a few times but never documented is to use a statement such as: Aneesha (on Twitter) is Aneesha (on Facebook). 

We don't currently have a verb for 'is' but we could register one on the registry. If we did, it would take the form `http://id.tincanapi.com/verb/is`.

**Comment by geirfp** [comment]
Garemoko, I realize the issue you opened is a very old one (and sadly, it seems that the CLA project is dormant), but I think your comment is very interesting. Do you know if something like you suggested have been done by others or have been formalized? It seems that the "is" verb is not found in the registry.

**Comment by garemoko** [comment]
Hi, 
I'm not sure anybody ever solved this problem in the way described above. In all the cases I'm aware of, personas are associated out of band from xAPI. 

At Watershed we have our own API endpoint and a CSV import tool that can be used to associate personas under a person.

**Comment by kirstykitto** [comment]
Yep - that is precisely what we are doing right now in the CLA toolkit. Planning a major upgrade of all this recipe work this year. Just waiting for the profile work to settle down and then we will test it out ;) But no - we wont be using is type statements when we do that.

**Comment by garemoko** [comment]
> Just waiting for the profile work to settle down and then we will test it out 

Nice! Actually, it might well be at the stage where an early test would be really useful for the profiles effort if you have time to do it.

**Comment by kirstykitto** [comment]
Yep - I had that thought too. Watching the updates. Just looking for some time to work on it, but teaching is over (well - wading through marking but that should be done soon), and it is moving up my list of priorities :) Right-o. Will see what we can do.
